### ISSUE TITLE
Add `aria-hidden=true` to sprite

### ISSUE THREAD

**Issue by ryuran** [Epimodev/svg-sprite-html-webpack#10]
Hello

For accessibility reasons we should hide svg sprites to screenreaders with aria attribute `aria-hidden="true"`.

**Comment by Epimodev** [comment]
Hello !

Thanks a lot for this suggestion 👍 
I'll fix that today or tomorrow :-)

**Comment by Epimodev** [comment]
I've just published version 2.3.0 with `aria-hidden` attribute.

Thanks again for this issue :-)
