### ISSUE TITLE
When used with webpack 4, you can see deprecation error

### ISSUE THREAD

**Issue by Tarjei400** [Epimodev/svg-sprite-html-webpack#3]
This is error message displayed by webpack 4 : 
```
(node:79479) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

Its coused by plugin.js : 158 in function apply.

**Comment by Epimodev** [comment]
Hi @Tarjei400 

Thanks for this feedback. I think there is this message because I keep compatibility with webpack 3.
I'll investigate deeply during next days to fix this  😀

**Comment by Epimodev** [comment]
Ok it's perfect thanks a lot. The way you fix it is pretty clean 👍
I've just push update to npm. It's version v2.1.1
